// settings.gradle（不使用 foojay 插件）

pluginManagement {
    repositories {
        gradlePluginPortal()

        maven {
            name = "MinecraftForge"
            url = "https://maven.minecraftforge.net/"
        }

        maven { url = "https://maven.parchmentmc.org" }

        maven { url = "https://bmclapi2.bangbang93.com/maven" }

        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)

    repositories {
        mavenCentral()

        maven {
            name = "MinecraftForge"
            url = "https://maven.minecraftforge.net/"
        }

        maven { url = "https://maven.parchmentmc.org" }

        // BMCL 镜像（备用源）
        maven { url = "https://bmclapi2.bangbang93.com/maven" }
    }
}

rootProject.name = "HBM-NTM-high-edition"