# -*- coding: utf-8 -*-
import json
import re
from pathlib import Path

EN_PATH = Path('src/generated/resources/assets/hbm/lang/en_us.json')
ZH_PATH = Path('src/main/resources/assets/hbm/lang/zh_cn.json')

WORD_MAP = {
    'a': '',
    'an': '',
    'the': '',
    'of': '的',
    'and': '与',
    'or': '或',
    'to': '到',
    'for': '用于',
    'by': '被',
    'with': '使用',
    'from': '来自',
    'in': '在',
    'on': '于',
    'at': '在',
    'per': '每',
    'up': '上',
    'down': '下',
    'left': '左',
    'right': '右',
    'start': '启动',
    'stop': '停止',
    'status': '状态',
    'running': '运行中',
    'idle': '空闲',
    'offline': '离线',
    'online': '在线',
    'insert': '插入',
    'insertion': '插入',
    'inserted': '已插入',
    'release': '释放',
    'retract': '抽回',
    'raise': '提升',
    'manual': '手动',
    'automatic': '自动',
    'automated': '自动化',
    'control': '控制',
    'controller': '控制器',
    'console': '控制台',
    'channel': '通道',
    'column': '反应柱',
    'columns': '反应柱',
    'peripheral': '外设',
    'machine': '机器',
    'generator': '发电机',
    'burner': '燃烧器',
    'battery': '电池',
    'energy': '能量',
    'storage': '存储',
    'block': '方块',
    'blocks': '方块',
    'core': '核心',
    'rod': '棒',
    'rods': '棒',
    'fuel': '燃料',
    'reactor': '反应堆',
    'rbmk': 'RBMK',
    'tokamak': '托卡马克',
    'heater': '加热器',
    'injector': '注入器',
    'port': '接口',
    'casing': '外壳',
    'base': '底座',
    'autoloader': '装填机',
    'crane': '起重机',
    'element': '元件',
    'reflector': '反射体',
    'debris': '碎屑',
    'console': '控制台',
    'coil': '线圈',
    'field': '场',
    'status': '状态',
    'heat': '热量',
    'coolant': '冷却剂',
    'steam': '蒸汽',
    'water': '水',
    'local': '本地',
    'global': '全局',
    'advanced': '高级',
    'data': '数据',
    'details': '详情',
    'show': '显示',
    'hide': '隐藏',
    'energy': '能量',
    'short': '简要',
    'offline': '离线',
    'running': '运行中',
    'warning': '警告',
    'critical': '危急',
    'fuel': '燃料',
    'progress': '进度',
    'heat': '热量',
    'loop': '回路',
    'control': '控制',
    'az-5': 'AZ-5',
    'barrel': '桶',
    'iron': '铁',
    'steel': '钢',
    'corroded': '腐蚀',
    'safe': '安全',
    'magnetic': '磁性',
    'container': '容器',
    'technetium': '锝',
    'chemical': '化工',
    'plant': '工厂',
    'debug': '调试',
    'depth': '深层',
    'stone': '石',
    'diesel': '柴油',
    'fire': '火',
    'ore': '矿石',
    'nether': '下界',
    'geiger': '盖格',
    'counter': '计数器',
    'glyphid': '格利夫',
    'spawner': '刷怪笼',
    'polluted': '污染',
    'water': '水',
    'launch': '发射',
    'pad': '平台',
    'wood': '木',
    'burner': '燃烧器',
    'generator': '发电机',
    'crate': '储箱',
    'assembler': '装配机',
    'boiler': '锅炉',
    'crucible': '坩埚',
    'difurnace': '高炉',
    'shredder': '粉碎机',
    'nuclear': '核',
    'electric': '电动',
    'furnace': '熔炉',
    'dineutronium': '二中子素',
    'lithium': '锂',
    'schrabidium': 'sa326',
    'spark': '火花',
    'storage': '存储',
    'block': '方块',
    'asbestos': '石棉',
    'launch': '发射',
    'pad': '平台',
    'container': '容器',
    'wood': '木',
    'ash': '灰',
    'powder': '粉末',
    'cell': '单元',
    'bucket': '桶',
    'ingot': '锭',
    'plate': '板',
    'nugget': '粒',
    'dust': '粉尘',
    'powder': '粉末',
    'ore': '矿石',
    'raw': '粗',
    'tiny': '微型',
    'small': '小型',
    'large': '大型',
    'huge': '巨型',
    'massive': '超大型',
    'basic': '基础',
    'advanced': '高级',
    'creative': '创造',
    'empty': '空',
    'filled': '充能',
    'balefire': '巴莱火',
    'uranium': '铀',
    'plutonium': '钚',
    'thorium': '钍',
    'americium': '镅',
    'neptunium': '镎',
    'actinium': '锕',
    'beryllium': '铍',
    'bismuth': '铋',
    'arsenic': '砷',
    'boron': '硼',
    'cadmium': '镉',
    'caesium': '铯',
    'calcium': '钙',
    'cerium': '铈',
    'cobalt': '钴',
    'coltan': '钶钽',
    'copper': '铜',
    'desh': '德什',
    'electronium': '电子素',
    'ferrouranium': '铁铀',
    'fiberglass': '玻璃纤维',
    'fluorite': '萤石',
    'graphite': '石墨',
    'gunmetal': '枪金',
    'gunsteel': '枪钢',
    'lead': '铅',
    'magnetized': '磁化',
    'magnet': '磁体',
    'mercury': '汞',
    'nickel': '镍',
    'niobium': '铌',
    'osmiridium': '锇铱',
    'polonium': '钋',
    'rubber': '橡胶',
    'sodium': '钠',
    'sulfur': '硫',
    'tantalium': '钽',
    'technetium': '锝',
    'titanium': '钛',
    'tungsten': '钨',
    'zirconium': '锆',
    'lithium': '锂',
    'aluminium': '铝',
    'aluminum': '铝',
    'silver': '银',
    'gold': '金',
    'red': '红',
    'blue': '蓝',
    'green': '绿',
    'yellow': '黄',
    'gray': '灰',
    'grey': '灰',
    'black': '黑',
    'white': '白',
    'purple': '紫',
    'pink': '粉',
    'brown': '棕',
    'bucket': '桶',
    'warhead': '弹头',
    'missile': '导弹',
    'part': '部件',
    'motor': '电机',
    'stage': '级',
    'thruster': '推进器',
    'tank': '储罐',
    'payload': '载荷',
    'scanner': '扫描器',
    'press': '压制机',
    'shredder': '粉碎机',
    'assembler': '装配机',
    'chemplant': '化工厂',
    'barrel': '桶',
    'crate': '储箱',
    'wood': '木',
    'burner': '燃烧器',
    'generator': '发电机',
    'electric': '电动',
    'furnace': '熔炉',
    'boiler': '锅炉',
    'battery': '电池',
    'storage': '存储',
    'block': '方块',
    'helmet': '头盔',
    'chestplate': '胸甲',
    'leggings': '护腿',
    'boots': '靴子',
    'armor': '护甲',
    'suit': '套装',
    'mask': '面罩',
    'backpack': '背包',
    'tool': '工具',
    'axe': '斧',
    'hoe': '锄',
    'shovel': '铲',
    'pickaxe': '镐',
    'sword': '剑',
    'knife': '刀',
    'pistol': '手枪',
    'rifle': '步枪',
    'shotgun': '霰弹枪',
    'launcher': '发射器',
    'bomb': '炸弹',
    'rocket': '火箭',
    'gun': '枪',
    'grenade': '手雷',
    'mine': '地雷',
    'detonator': '起爆器',
    'nuke': '核弹',
    'rtg': '放射性同位素电源',
    'pellet': '燃料团',
    'cell': '单元',
    'capsule': '舱',
    'module': '模块',
    'circuit': '电路',
    'capacitor': '电容',
    'controller': '控制器',
    'chip': '芯片',
    'board': '板',
    'panel': '面板',
    'console': '控制台',
    'monitor': '监视器',
    'screen': '屏幕',
    'port': '接口',
    'slot': '槽',
    'slots': '槽位',
    'inventory': '背包',
    'tooltip': '提示',
    'warning': '警告',
    'danger': '危险',
    'time': '时间',
    'remaining': '剩余',
    'seconds': '秒',
    'ticks': '刻',
    'per': '每',
    'tick': '刻',
    'mb': 'mB',
    'he': 'HE',
    'cooling': '冷却',
    'consumption': '消耗',
    'speed': '速度',
    'efficiency': '效率',
    'productivity': '产能',
    'fortune': '时运',
    'range': '范围',
    'acid': '酸',
    'burn': '燃烧',
    'delay': '延迟',
    'upgrade': '升级',
    'tooltip': '提示',
    'empty': '空',
    'enabled': '启用',
    'disabled': '禁用',
    'remaining': '剩余',
}

EXTRA_WORD_MAP = {
    'active': '激活',
    'adjust': '调节',
    'aelectron': '逆电子',
    'ajr': 'AJR',
    'ajro': 'AJRO',
    'alexandrite': '紫翠玉',
    'alloy': '合金',
    'alt': 'Alt键',
    'am': '镅',
    'am241': '镅-241',
    'am242': '镅-242',
    'amat': '反物质',
    'ams': 'AMS系统',
    'anti': '反',
    'antimatter': '反物质',
    'aproton': '反质子',
    'aschrab': '反sa326',
    'assembly': '装配',
    'astatine': '砹',
    'at209': '砹-209',
    'au198': '金-198',
    'australium': '澳洲金',
    'bakelite': '电木',
    'ball': '球体',
    'basalt': '玄武岩',
    'bedrock': '基岩',
    'bf': 'BF（巴莱火）',
    'big': '大型',
    'billet': '坯料',
    'bio': '生物',
    'biomass': '生物质',
    'biorubber': '生物橡胶',
    'birth': '孵化',
    'bj': 'BJ',
    'blade': '刀刃',
    'blank': '空白',
    'bolt': '螺栓',
    'borax': '硼砂',
    'bottle': '瓶',
    'bromine': '溴',
    'bronze': '青铜',
    'bscco': 'BSCCO超导体',
    'buffers': '缓冲',
    'buster': '粉碎者',
    'byproduct': '副产物',
    'c4': 'C4炸药',
    'cake': '蛋糕',
    'can': '罐',
    'catalyst': '催化剂',
    'cdalloy': 'CD合金',
    'cement': '水泥',
    'centrifuge': '离心机',
    'centrifuged': '离心处理',
    'cft': 'CFT合金',
    'chainsteel': '链钢',
    'chlorine': '氯',
    'chlorocalcite': '氯方解石',
    'chlorophyte': '叶绿矿',
    'cinnebar': '辰砂',
    'clay': '黏土',
    'cleaned': '净化',
    'closed': '关闭',
    'cloth': '布料',
    'cluster': '集束',
    'cmb': 'CMB',
    'co60': '钴-60',
    'coal': '煤',
    'combine': '组合',
    'compressed': '压缩',
    'consider': '考虑',
    'crayon': '蜡笔',
    'crt': '显像管',
    'crystal': '晶体',
    'cs137': '铯-137',
    'dagaz': '达伽兹',
    'dalekanium': '戴立克合金',
    'damp': '潮湿',
    'dark': '黑暗',
    'deepcleaned': '深度清洁',
    'deepslate': '深板岩',
    'demon': '恶魔',
    'deuterium': '氘',
    'diamond': '钻石',
    'dieselsuit': '柴油套装',
    'digamma': '双伽马',
    'display': '显示',
    'dnt': 'DNT炸药',
    'drag': '拖拽',
    'drill': '钻头',
    'duct': '管道',
    'ducttape': '布基胶带',
    'dura': '杜拉',
    'during': '期间',
    'dusted': '除尘',
    'dye': '染料',
    'dysfunctional': '损坏',
    'earth': '泥土',
    'egg': '卵',
    'emerald': '绿宝石',
    'emergency': '紧急',
    'end': '末地',
    'enriched': '浓缩',
    'entanglement': '纠缠',
    'entire': '全部',
    'euphemium': '尤菲米姆',
    'every': '每个',
    'fallout': '核尘',
    'fau': 'FAU',
    'fertilizer': '肥料',
    'filter': '过滤器',
    'fins': '鳍片',
    'firebrick': '耐火砖',
    'flashlead': '闪铅',
    'flat': '平面',
    'flux': '助焊剂',
    'flywheel': '飞轮',
    'forged': '锻造',
    'fragment': '碎片',
    'full': '充满',
    'fully': '完全',
    'fuse': '保险丝',
    'gas': '气体',
    'gear': '齿轮',
    'gem': '宝石',
    'generic': '通用',
    'genetic': '基因',
    'geniss': '吉尼斯',
    'gh336': 'GH336合金',
    'glypid': '格利夫',
    'greater': '更强',
    'grilled': '炙烤',
    'hagalaz': '哈加拉兹',
    'handle': '把手',
    'hazmat': '防化',
    'head': '头部',
    'hev': 'HEV',
    'higgs': '希格斯',
    'hot': '高温',
    'hydrogen': '氢',
    'i131': '碘-131',
    'immediately': '立即',
    'impure': '未净化',
    'incendiary': '燃烧',
    'infernal': '地狱',
    'iodine': '碘',
    'irradiated': '辐照',
    'isa': '伊萨',
    'jera': '耶拉',
    'jetpack': '喷气背包',
    'kevlar': '凯夫拉',
    'kit': '套件',
    'lanthanium': '镧',
    'lapis': '青金石',
    'laser': '激光',
    'layser': '激光',
    'leaves': '树叶',
    'legs': '护腿',
    'les': '莱斯',
    'lesser': '次级',
    'limestone': '石灰石',
    'linked': '已链接',
    'loaded': '已装填',
    'locked': '锁定',
    'low': '低',
    'lunar': '月球',
    'lutece': '吕特斯',
    'magic': '魔法',
    'mapper': '映射器',
    'meat': '肉',
    'medium': '中型',
    'meteorite': '陨石',
    'mirv': '分导弹头',
    'mix': '混合',
    'mixed': '混合',
    'molysite': '钼矿',
    'more': '更多',
    'mox': '混合氧化物',
    'mud': '泥浆',
    'muon': '介子',
    'neodymium': '钕',
    'neutron': '中子',
    'nitan': '硝基',
    'niter': '硝石',
    'nitra': '硝粉',
    'nitrated': '硝化',
    'nitrocrystalline': '硝基晶体',
    'no': '无',
    'nominal': '标称',
    'oil': '油',
    'open': '打开',
    'override': '覆写',
    'paa': 'PAA装甲',
    'paleogenite': '古源石',
    'particle': '粒子',
    'pb209': '铅-209',
    'pc': 'PC',
    'pedestal': '底座',
    'ph0': 'PH0',
    'ph1': 'PH1',
    'ph2': 'PH2',
    'phosphorus': '磷',
    'photo': '光',
    'pile': '堆',
    'pinwheel': '风车',
    'pipe': '管',
    'pipes': '管道',
    'piss': '尿液',
    'piston': '活塞',
    'po210be': '钋-210铍',
    'polymer': '聚合物',
    'power': '功率',
    'presto': '普雷斯托',
    'pu': '钚',
    'pu238': '钚-238',
    'pu238be': '钚-238铍',
    'pu239': '钚-239',
    'pu240': '钚-240',
    'pu241': '钚-241',
    'puf6': '六氟化钚',
    'purified': '净化',
    'pvc': '聚氯乙烯',
    'quad': '四联',
    'quartz': '石英',
    'ra226': '镭-226',
    'ra226be': '镭-226铍',
    'rad': '辐射',
    'radar': '雷达',
    'radium': '镭',
    'rag': '抹布',
    'rare': '稀有',
    'ready': '就绪',
    'redstone': '红石',
    'refill': '重新填充',
    'resin': '树脂',
    'resonator': '谐振器',
    'response': '响应',
    'ring': '环',
    'robes': '长袍',
    'route': '路径',
    'rpa': 'RPA装甲',
    'rune': '符文',
    'sa326': 'sa326',
    'safety': '安全',
    'salpeter': '硝石',
    'sand': '砂',
    'sas3': 'SAS3炸药',
    'sat': '卫星',
    'saturnite': '土星合金',
    'sawblade': '锯片',
    'sawdust': '锯屑',
    'schrabidate': '施拉比酸盐',
    'schraranium': '施拉兰',
    'scorched': '灼烧',
    'scram': '紧急停堆',
    'scrap': '废料',
    'seared': '灼烧',
    'security': '安保',
    'seg': 'SEG',
    'selenium': '硒',
    'sellafield': '塞拉菲尔德',
    'semtex': '塞姆特炸药',
    'separated': '分离',
    'set': '设置',
    'shell': '外壳',
    'shimmer': '闪烁',
    'silicon': '硅',
    'slaked': '熟化',
    'slider': '滑块',
    'smolder': '阴燃',
    'smore': '斯莫尔',
    'sodalite': '方钠石',
    'solid': '固体',
    'solinium': '索利尼姆',
    'sparkticle': '火花粒子',
    'sphere': '球体',
    'spike': '尖刺',
    'sr90': '锶-90',
    'stack': '堆叠',
    'star': '星',
    'starmetal': '星陨金属',
    'steamsuit': '蒸汽套装',
    'strange': '奇异',
    'strontium': '锶',
    'suicide': '自毁',
    'sulfuric': '硫酸',
    't51': 'T-51',
    'tachyon': '超光速子',
    'tape': '胶带',
    'tcalloy': 'TC合金',
    'tektite': '玻陨石',
    'tennessine': '鿭',
    'th232': '钍-232',
    'them': '他们',
    'throughput': '吞吐量',
    'thurisaz': '索鲁萨兹',
    'tikite': '提凯特',
    'toothpicks': '牙签',
    'torus': '环体',
    'tri': '三联',
    'trip': '旅程',
    'triplet': '三重',
    'tritium': '氚',
    'trixite': '特里克石',
    'turbine': '涡轮',
    'u233': '铀-233',
    'u235': '铀-235',
    'u238': '铀-238',
    'u238m2': '铀-238M2',
    'uf6': '六氟化铀',
    'unit': '单元',
    'unlock': '解锁',
    'used': '已使用',
    'volcanic': '火山的',
    'volcano': '火山',
    'wafer': '晶圆',
    'wast': '荒原',
    'waste': '废料',
    'weak': '微弱',
    'will': '将',
    'wire': '导线',
    'wiring': '布线',
    'xe135': '氙-135',
    'yellowcake': '黄饼',
    'yharonite': '亚罗石',
    'you': '你',
    'zfb': 'ZFB',
}

WORD_MAP.update(EXTRA_WORD_MAP)

WORD_MAP.update({
    'abilities': '能力',
    'actually': '实际上',
    'all': '全部',
    'allows': '允许',
    'also': '也',
    'alter': '改变',
    'anvil': '铁砧',
    'are': '是',
    'backward': '倒退',
    'bang': '爆炸',
    'best': '最佳',
    'blackhole': '黑洞',
    'blacklung': '尘肺',
    'blast': '冲击',
    'boat': '船',
    'boxcar': 'Boxcar',
    'broadcast': '广播',
    'broken': '损坏',
    'building': '建筑',
    'burned': '燃毁',
    'but': '但',
    'cached': '缓存',
    'calculator': '计算器',
    "can't": '无法',
    'capacity': '容量',
    'chance': '几率',
    'cheater': '作弊者',
    'chunk': '区块',
    'cloud': '云',
    'coke': '焦炭',
    'combustible': '可燃',
    'configure': '配置',
    'copy': '复制',
    'corrosive': '腐蚀性',
    'crunches': '咔嚓作响',
    'cycle': '循环',
    'dash': '冲刺',
    'delicious': '美味',
    'dev': '开发者',
    'easy': '简单',
    'electricity': '电力',
    'enervation': '衰竭',
    'enough': '足够',
    'error': '错误',
    'euthanized': '安乐死',
    'exhaust': '排气',
    'explanatory': '说明',
    'flammable': '易燃',
    'forcefield': '力场',
    'forward': '前进',
    'found': '发现',
    'friend': '朋友',
    'fumes': '烟雾',
    'fusion': '聚变',
    'gaseous': '气态',
    'goes': '会',
    'grade': '等级',
    'half': '半',
    'hazardous': '危险',
    'hbm': 'HBM',
    'health': '生命',
    'help': '帮助',
    'here': '此处',
    'heuf6': 'HEUF6',
    'hold': '按住',
    'hopefully': '希望',
    'hotkeys': '热键',
    'hud': 'HUD',
    'ignored': '已忽略',
    'ion': '离子',
    'is': '是',
    'isotopic': '同位素',
    'it': '它',
    'item': '物品',
    'items': '物品',
    'khe': 'kHE',
    'killed': '被击杀',
    'li': '锂',
    'life': '生命',
    'like': '如同',
    'liion': '锂离子',
    'liquid': '液体',
    'load': '装填',
    'lot': '大量',
    'mario': '马里奥',
    'material': '材料',
    'max': '最大',
    'microwave': '微波',
    'mining': '采矿',
    'missing': '缺失',
    'mku': 'MKU',
    'mode': '模式',
    'modified': '已修改',
    'monoxide': '一氧化物',
    'move': '移动',
    'multiplier': '倍率',
    'new': '新',
    'not': '不',
    'ntm': 'NTM',
    'null': '空',
    'overdose': '过量',
    'paste': '糊剂',
    'pheromones': '信息素',
    'please': '请',
    'poison': '毒素',
    'polluting': '污染',
    'pos': '坐标',
    'primary': '主',
    'process': '处理',
    'provides': '提供',
    'pwr': '压水堆',
    'radiation': '辐射',
    'radioactive': '放射性',
    'radius': '半径',
    'recipe': '配方',
    'registered': '已注册',
    'reload': '重新装填',
    'required': '需要',
    'requires': '需要',
    'room': '房间',
    'rubble': '碎石',
    's': '',
    'scientists': '科学家',
    'scream': '尖叫',
    'secondary': '次级',
    'self': '自身',
    'separation': '分离',
    'shrapnel': '弹片',
    'sicko': '疯子',
    'sights': '瞄具',
    'siphon': '虹吸',
    'smelts': '熔炼',
    'spilled': '泼洒',
    'strongly': '强烈',
    'subautomic': '亚原子',
    'super': '超级',
    'switch': '开关',
    't': 'T',
    'taint': '污秽',
    'tau': 'τ',
    'teleporter': '传送器',
    'temperature': '温度',
    'thermal': '热能',
    'they': '他们',
    'tier': '等级',
    'toads': '奇诺比奥',
    'toggle': '切换',
    'total': '总计',
    'toxic': '有毒',
    'train': '列车',
    'tu': 'TU',
    'turbofan': '涡扇',
    'unload': '卸载',
    'vacuum': '真空',
    'viscous': '粘稠',
    'wait': '等待',
    'when': '当',
    'where': '在何处',
    'worthless': '毫无价值',
    'your': '你的',
    'zero': '零',
})

PHRASE_MAP = {
    'Energy Storage Block': '能量存储块',
    'RBMK Fuel Channel': 'RBMK燃料通道',
    'RBMK Control Rod': 'RBMK控制棒',
    'RBMK Control Rod Channel': 'RBMK控制棒通道',
    'RBMK Control Console': 'RBMK控制台',
    'RBMK Crane Console': 'RBMK起重机控制台',
    'RBMK Autoloader': 'RBMK自动装填机',
    'Tokamak Field Coil': '托卡马克场线圈',
    'Tokamak Controller': '托卡马克控制器',
    'Tokamak Casing': '托卡马克外壳',
    'Tokamak Heater': '托卡马克加热器',
    'Tokamak Injector': '托卡马克注入器',
    'Tokamak Port': '托卡马克接口',
}

PHRASE_MAP.update({
    'Tier 1 anvil': '一级铁砧',
    'Blast Furnace': '高炉',
    'Li-Ion Energy Storage Block': '锂离子能量存储块',
    'Spark Energy Storage Block': '火花能量存储块',
    'Nuclear Oil Heater': '核油加热器',
})

PLACEHOLDER_RE = re.compile(r"%[0-9]*\$?[sd]" )
WORD_RE = re.compile(r"[A-Za-z][A-Za-z0-9'\-]*")
CJK_RE = re.compile(r"[\u4e00-\u9fff]")

missing_words = set()
ALLOWED_LATIN = {
    'RBMK', 'HBM', 'AZ-5', 'HUD', 'HE', 'HEU', 'mB', 'mB/t', 'HEUF6',
    'UF6', 'RTG', 'NTM', 'AMS', 'AJR', 'AJRO', 'PAA', 'RPA', 'BSCCO',
    'CMB', 'SEG', 'MKU', 'MKV', 'MKVI', 'Mk', 'MkV', 'MkVI', 'TNT',
    'Boxcar', 'kHE', 'M2',
}

def is_cjk(text:str)->bool:
    return bool(CJK_RE.search(text))

def should_replace(existing: str) -> bool:
    if not existing:
        return True
    cleaned = PLACEHOLDER_RE.sub('', existing)
    latin_tokens = WORD_RE.findall(cleaned)
    if latin_tokens:
        extras = [tok for tok in latin_tokens if len(tok) > 1 and tok not in ALLOWED_LATIN]
        if extras:
            return True
    if '（原文）' in existing:
        return True
    return False

def translate_word(word:str)->str:
    clean = word.lower()
    if clean.endswith("'s"):
        clean = clean[:-2]
    if clean in WORD_MAP:
        return WORD_MAP[clean]
    # handle plural s
    if clean.endswith('s') and clean[:-1] in WORD_MAP:
        return WORD_MAP[clean[:-1]]
    if '-' in clean:
        parts = [translate_word(p) for p in clean.split('-')]
        if any(p for p in parts):
            result = ''.join(parts)
            if result:
                return result
    if clean:
        missing_words.add(clean)
    return word

def apply_phrase_map(text:str)->str:
    for en, zh in PHRASE_MAP.items():
        text = text.replace(en, zh)
    return text


def translate_generic(text:str)->str:
    placeholders = []
    def ph_repl(match):
        placeholders.append(match.group(0))
        return f"__PH{len(placeholders)-1}__"
    temp = PLACEHOLDER_RE.sub(ph_repl, text)
    temp = apply_phrase_map(temp)

    def word_repl(match):
        word = match.group(0)
        if word.startswith('__PH'):
            return word
        return translate_word(word)

    temp = WORD_RE.sub(word_repl, temp)
    for idx, ph in enumerate(placeholders):
        temp = temp.replace(f"__PH{idx}__", ph)
    temp = re.sub(r"(?<=[\u4e00-\u9fff]) (?=[\u4e00-\u9fff])", '', temp)
    temp = temp.strip()
    if not is_cjk(temp):
        temp = f"{temp}（原文）"
    return temp


def translate_entry(key:str, value:str)->str:
    return translate_generic(value)


def main():
    en_data = json.loads(EN_PATH.read_text(encoding='utf-8'))
    if ZH_PATH.exists():
        zh_existing = json.loads(ZH_PATH.read_text(encoding='utf-8'))
    else:
        zh_existing = {}
    zh_new = {}
    for key, value in en_data.items():
        if key in zh_existing:
            if should_replace(zh_existing[key]):
                zh_new[key] = translate_entry(key, value)
            else:
                zh_new[key] = zh_existing[key]
        else:
            zh_new[key] = translate_entry(key, value)
    ZH_PATH.write_text(json.dumps(zh_new, ensure_ascii=False, indent=2, sort_keys=False), encoding='utf-8')
    missing_path = Path('build') / 'missing_words.txt'
    if missing_words:
        missing_path.parent.mkdir(exist_ok=True)
        missing_path.write_text('\n'.join(sorted(missing_words)), encoding='utf-8')
        print(f"Missing words exported: {len(missing_words)}")
    elif missing_path.exists():
        missing_path.unlink()

if __name__ == '__main__':
    main()
